### ISSUE TITLE
Official maps are unavailable for self-hosted instances, rendering the majority of the game unplayable

### ISSUE THREAD

**Issue by ninjadev64** [benlikescode/geohub#105] opened 2024-06-21 21:39 UTC
Per the (brief) discussion in #98:
> You have to add your own maps. What I may do in the future is set it up with 100 or so locations per map, I just don't want all the locations publicly viewable.

For context, I'm self-hosting because geohub.gg is blocked in my school. Surely asking users to create their own maps from scratch is a huge ask? And realistically, what are the motives for cheating on geohub.gg? (and how would you feasibly go about cheating having been given access to the data, anyway?)

Please could you make the official maps available to download.

**Comment by ninjadev64** [comment] 2024-06-21 21:54
~~In other words, could you comment out [this line](https://github.com/benlikescode/geohub/blob/87f72ac6aabeadb7124aff3f4958194c58b56e45/backend/routes/maps/getCustomMap.ts#L21)?~~

**Comment by Paillat-dev** [comment] 2024-06-26 09:21
The maps are from my understanding not *there* in the database, so it's not about commenting out a line.

**Comment by Paillat-dev** [comment] 2024-06-26 09:22
Also this is a duplicate of #101

**Closed** 2024-08-19 11:03 UTC
