### ISSUE TITLE
Bug Country Streak

### ISSUE THREAD

**Issue by aware2** [benlikescode/geohub#24] opened 2023-07-09 15:47 UTC
Hi,

In Streak mode, it's impossible to guess Lesotho and Taiwan.
Also a bug on the border between Kyrgyzstan and Uzbekistan.
![geohub_bug](https://github.com/benlikescode/geohub/assets/17573738/356b58a9-745c-439c-9a75-794e689b2454)

Thank you

**Comment by benlikescode** [comment] 2023-07-10 04:09
Thanks for reporting this. I just pushed an update that fixes Taiwan & Lesotho! 

What exactly is the issue in the image you attached? If it's the country outline not being perfectly aligned with Google Maps, that is expected behavior when you zoom in a lot since the bounds file would be huge otherwise.

**Comment by aware2** [comment] 2023-07-10 04:23
Hi,

Thx fo this update.
The issue in the image : I guessed Kyrgyzstan (that's right) but i lost : "Uzbekistan - You guessed Kyrgyzstan"

**Comment by benlikescode** [comment] 2023-07-10 04:38
Ahh I see, there are a few locations that are in Kyrgyzstan but for some reason are marked as being Uzbekistan. 

I have removed these locations for the future. 

Thanks again for reporting these issues!

**Closed** 2023-07-12 00:26 UTC
